// Generated by CoffeeScript 1.3.3
(function() {
  var $h1, $line, $point, $svg, $window, B_21, B_22, B_23, B_31, B_32, B_33, B_34, Point, bezier_2, bezier_3, drawLine, initX, initY, p_0, p_1, p_2, p_3, scrollableArea, updateLine;

  $window = $(window);

  $line = $('#line');

  $point = $('#point');

  $svg = $('svg');

  $h1 = $('h1');

  initY = 300;

  initX = $window.width() / 2;

  Point = function(x, y) {
    if (!x) {
      x = 0;
    }
    if (!y) {
      y = 0;
    }
    return {
      x: x,
      y: y
    };
  };

  B_21 = function(t) {
    return t * t;
  };

  B_22 = function(t) {
    return 2 * t * (1 - t);
  };

  B_23 = function(t) {
    return (1 - t) * (1 - t);
  };

  B_31 = function(t) {
    return t * t * t;
  };

  B_32 = function(t) {
    return 3 * t * t * (1 - t);
  };

  B_33 = function(t) {
    return 3 * t * (1 - t) * (1 - t);
  };

  B_34 = function(t) {
    return (1 - t) * (1 - t) * (1 - t);
  };

  bezier_2 = function(t, p1, p2, p3) {
    var r;
    r = Point();
    r.x = Math.ceil(p1.x * B_21(t) + p2.x * B_22(t) + p3.x * B_23(t));
    r.y = Math.ceil(p1.y * B_21(t) + p2.y * B_22(t) + p3.y * B_23(t));
    return r;
  };

  bezier_3 = function(t, p1, p2, p3, p4) {
    var r;
    r = Point();
    r.x = Math.ceil(p1.x * B_31(t) + p2.x * B_32(t) + p3.x * B_33(t) + p4.x * B_34(t));
    r.y = Math.ceil(p1.y * B_31(t) + p2.y * B_32(t) + p3.y * B_33(t) + p4.y * B_34(t));
    return r;
  };

  p_0 = Point(initX, initY);

  p_1 = Point(initX - 200, initY + 200);

  p_2 = Point(initX + 200, 700);

  p_3 = Point(initX, 700);

  drawLine = function(p0, p1, p2, p3) {
    return $line.attr("d", "M " + p0.x + ", " + p0.y + " Q " + p1.x + ", " + p1.y + " " + p2.x + ", " + p2.y + " T " + p3.x + ", " + p3.y);
  };

  scrollableArea = $('body').height() - $window.height();

  updateLine = function(t, p0, p1, p2, p3) {
    var c, q;
    q = bezier_3(t, p0, p1, p2, p3);
    c = bezier_2(t, p0, p1, q);
    return drawLine(p0, p1, c, q);
  };

  updateLine(0, p_0, p_1, p_2, p_3);

  $window.scroll(function() {
    var t;
    t = $window.scrollTop() / scrollableArea;
    if (t > 1) {
      t = 1;
    }
    $h1.css('top', 240 + Math.ceil($window.scrollTop() * $h1.data('speed')));
    p_0 = Point(initX, initY + Math.ceil($window.scrollTop() * $svg.data('speed')));
    return updateLine(t, p_0, p_1, p_2, p_3);
  });

}).call(this);
