// Generated by CoffeeScript 1.3.3
(function() {
  var $h1, $line, $point, $svg, $window, initX;

  $window = $(window);

  $line = $('#line');

  $point = $('#point');

  $svg = $('svg');

  $h1 = $('h1');

  initX = $window.width() / 2;

}).call(this);
